before_install:
  - date
  - uname -a
  - ulimit -a
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - cat /etc/apt/sources.list
  - git fetch --tags
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install haskell-platform gcc make openjdk-7-jdk ant
  - wget http://dl.google.com/android/android-sdk_r15-linux.tgz
  - wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2
  - tar xf android-sdk_r15-linux.tgz
  - tar xf android-ndk-r9-linux-x86_64.tar.bz2
  - mv android-ndk-r9 android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - echo $PATH
  - echo "y" | android update sdk --filter platform-tool,tool --no-ui --force
  - echo "y" | android update sdk --filter android-10 --no-ui --force
  - git --version
  - ghc --version
  - ndk-build --version
  - android list
script:
  - make
after_script:
  - date
